### ISSUE TITLE
Error: while make command

### ISSUE THREAD

**Issue by anurag-iitk** [0xPolygon/cdk-erigon#1635]
make cdk-erigon

Building cdk-erigon
# github.com/ledgerwatch/erigon/cmd/cdk-erigon
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/g++ -m64 -o $WORK/b001/exe/a.out -rdynamic -Wl,--compress-debug-sections=zlib /tmp/go-link-832749308/go.o /tmp/go-link-832749308/000000.o /tmp/go-link-832749308/000001.o /tmp/go-link-832749308/000002.o /tmp/go-link-832749308/000003.o /tmp/go-link-832749308/000004.o /tmp/go-link-832749308/000005.o /tmp/go-link-832749308/000006.o /tmp/go-link-832749308/000007.o /tmp/go-link-832749308/000008.o /tmp/go-link-832749308/000009.o /tmp/go-link-832749308/000010.o /tmp/go-link-832749308/000011.o /tmp/go-link-832749308/000012.o /tmp/go-link-832749308/000013.o /tmp/go-link-832749308/000014.o /tmp/go-link-832749308/000015.o /tmp/go-link-832749308/000016.o /tmp/go-link-832749308/000017.o /tmp/go-link-832749308/000018.o /tmp/go-link-832749308/000019.o /tmp/go-link-832749308/000020.o /tmp/go-link-832749308/000021.o /tmp/go-link-832749308/000022.o /tmp/go-link-832749308/000023.o /tmp/go-link-832749308/000024.o /tmp/go-link-832749308/000025.o /tmp/go-link-832749308/000026.o /tmp/go-link-832749308/000027.o /tmp/go-link-832749308/000028.o /tmp/go-link-832749308/000029.o /tmp/go-link-832749308/000030.o /tmp/go-link-832749308/000031.o /tmp/go-link-832749308/000032.o /tmp/go-link-832749308/000033.o /tmp/go-link-832749308/000034.o /tmp/go-link-832749308/000035.o /tmp/go-link-832749308/000036.o /tmp/go-link-832749308/000037.o /tmp/go-link-832749308/000038.o /tmp/go-link-832749308/000039.o /tmp/go-link-832749308/000040.o /tmp/go-link-832749308/000041.o /tmp/go-link-832749308/000042.o /tmp/go-link-832749308/000043.o /tmp/go-link-832749308/000044.o /tmp/go-link-832749308/000045.o /tmp/go-link-832749308/000046.o /tmp/go-link-832749308/000047.o /tmp/go-link-832749308/000048.o /tmp/go-link-832749308/000049.o /tmp/go-link-832749308/000050.o /tmp/go-link-832749308/000051.o /tmp/go-link-832749308/000052.o /tmp/go-link-832749308/000053.o -O2 -g -fPIC -O2 -g -lpthread -O2 -g -O2 -g -lrt -O2 -g -O2 -g -O2 -g -O2 -g -lsilkworm_capi -L/home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64 -Wl,-rpath,$ORIGIN -Wl,-rpath,$ORIGIN/../lib -Wl,-rpath /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64 -no-pie
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlopen@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setrobust@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setprotocol@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_init@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `fstat64@GLIBC_2.33'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_condattr_setclock@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlerror@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `stat64@GLIBC_2.33'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const &@GLIBCXX_3.4.29'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_attr_setstacksize@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `__libc_single_threaded@GLIBC_2.32'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setpshared@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_setname_np@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_once@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::to_chars(char*, char*, double)@GLIBCXX_3.4.29'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dladdr@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_destroy@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_key_create@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_unlock@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutex_consistent@GLIBC_2.34'
/usr/bin/ld: /home/anurag/go/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `lstat64@GLIBC_2.33'
collect2: error: ld returned 1 exit status

make: *** [Makefile:114: cdk-erigon.cmd] Error 1

 ldd --version

ld.so (GNU libc) stable release version 2.34.
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

**Comment by revitteth** [comment]
Couple of questions:

- cdk-erigon commit/tag/version?
- go version?
- OS and OS version?

**Comment by TurtleSnail** [comment]
same issue:
```
# make cdk-erigon
Building cdk-erigon
# github.com/ledgerwatch/erigon/cmd/cdk-erigon
/root/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/g++ -m64 -o $WORK/b001/exe/a.out -rdynamic -Wl,--compress-debug-sections=zlib /tmp/go-link-390785761/go.o /tmp/go-link-390785761/000000.o /tmp/go-link-390785761/000001.o /tmp/go-link-390785761/000002.o /tmp/go-link-390785761/000003.o /tmp/go-link-390785761/000004.o /tmp/go-link-390785761/000005.o /tmp/go-link-390785761/000006.o /tmp/go-link-390785761/000007.o /tmp/go-link-390785761/000008.o /tmp/go-link-390785761/000009.o /tmp/go-link-390785761/000010.o /tmp/go-link-390785761/000011.o /tmp/go-link-390785761/000012.o /tmp/go-link-390785761/000013.o /tmp/go-link-390785761/000014.o /tmp/go-link-390785761/000015.o /tmp/go-link-390785761/000016.o /tmp/go-link-390785761/000017.o /tmp/go-link-390785761/000018.o /tmp/go-link-390785761/000019.o /tmp/go-link-390785761/000020.o /tmp/go-link-390785761/000021.o /tmp/go-link-390785761/000022.o /tmp/go-link-390785761/000023.o /tmp/go-link-390785761/000024.o /tmp/go-link-390785761/000025.o /tmp/go-link-390785761/000026.o /tmp/go-link-390785761/000027.o /tmp/go-link-390785761/000028.o /tmp/go-link-390785761/000029.o /tmp/go-link-390785761/000030.o /tmp/go-link-390785761/000031.o /tmp/go-link-390785761/000032.o /tmp/go-link-390785761/000033.o /tmp/go-link-390785761/000034.o /tmp/go-link-390785761/000035.o /tmp/go-link-390785761/000036.o /tmp/go-link-390785761/000037.o /tmp/go-link-390785761/000038.o /tmp/go-link-390785761/000039.o /tmp/go-link-390785761/000040.o /tmp/go-link-390785761/000041.o /tmp/go-link-390785761/000042.o /tmp/go-link-390785761/000043.o /tmp/go-link-390785761/000044.o /tmp/go-link-390785761/000045.o /tmp/go-link-390785761/000046.o /tmp/go-link-390785761/000047.o /tmp/go-link-390785761/000048.o /tmp/go-link-390785761/000049.o /tmp/go-link-390785761/000050.o /tmp/go-link-390785761/000051.o /tmp/go-link-390785761/000052.o /tmp/go-link-390785761/000053.o -O2 -g -fPIC -O2 -g -lpthread -O2 -g -O2 -g -lrt -O2 -g -O2 -g -O2 -g -O2 -g -lsilkworm_capi -L/root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64 -Wl,-rpath,$ORIGIN -Wl,-rpath,$ORIGIN/../lib -Wl,-rpath /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64 -no-pie
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlopen@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setrobust@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setprotocol@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()@GLIBCXX_3.4.29'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_init@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `fstat64@GLIBC_2.33'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_condattr_setclock@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlerror@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__throw_bad_array_new_length()@GLIBCXX_3.4.29'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `stat64@GLIBC_2.33'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const &@GLIBCXX_3.4.29'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_attr_setstacksize@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_release()@CXXABI_1.3.13'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `__libc_single_threaded@GLIBC_2.32'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutexattr_setpshared@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_detach@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::__exception_ptr::exception_ptr::_M_addref()@CXXABI_1.3.13'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_setname_np@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_once@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `std::to_chars(char*, char*, double)@GLIBCXX_3.4.29'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dladdr@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_destroy@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_key_create@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_rwlock_unlock@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `pthread_mutex_consistent@GLIBC_2.34'
/usr/bin/ld: /root/gopath/pkg/mod/github.com/erigontech/silkworm-go@v0.18.0/lib/linux_x64/libsilkworm_capi.so: undefined reference to `lstat64@GLIBC_2.33'
collect2: error: ld returned 1 exit status

make: *** [Makefile:114: cdk-erigon.cmd] Error 1
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

```
# go version
go version go1.23.5 linux/amd64
```

```
# git status
HEAD detached at v2.60.2
nothing to commit, working tree clean
```

**Comment by TurtleSnail** [comment]
fyi, builds on 24.04

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

but it should be possible to build on 20.04 ?

**Comment by TurtleSnail** [comment]
fwiw, also compiles on 22.04
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

**Comment by elliothllm** [comment]
It seems g++ 12 or higher is needed to build CDK-Erigon so you will need Ubuntu 22.04 or higher.
